### ISSUE TITLE
Only shows Venom poster when movie is paused

### ISSUE THREAD

**Issue by icpryde** [123Venom/zips#2]
Hi,

I enjoy your addon and just wanted to bring to your attention when you pause a movie and have the setting ' display poster and plot when video is paused ' it only shows the poster of venom instead of the movie poster.

I'm using the Aura Skin as well if that helps.

**Comment by icpryde** [comment]
After further testing, I notice it only displays the venom poster when I play a movie from a widget but if I play the movie from the categories sections like "most popular" it shows the proper poster.

**Comment by 123Venom** [comment]
I've had 3 ppl try to replicate this issue with Aura skin and one of them spoke to you.  This seems to occur from widgets I understand?  I've tried everything I can think of and can not reproduce the issue.  Everything produces the movie poster for Bohemian Rhapsody that I've tested.  Have you tried using Aftermath and clearing all cache, system and addon wide?
