### ISSUE TITLE
Trakt Lists

### ISSUE THREAD

**Issue by fungusfeet** [123Venom/zips#3]
There is an issue with tvshows.py in resources/lib/indexers.  Trakt lists for tvshows do not load, error getting directory after calling plugin.

I'm not sure what the error is but I replaced tvshows.py with the one from exodusredux and it works now (but does not hide watched)

**Comment by 123Venom** [comment]
Just tested this and added/removed items from my own list online and it tested fine.  Try clearing all cache see if that fixes it.
![Capture](https://user-images.githubusercontent.com/46383815/57408230-17916500-71b3-11e9-8838-aa3bfbbf1ff7.JPG)

**Comment by fungusfeet** [comment]
I take it test4 is an actual list with shows added to it? Does it actually load the list when you click it?

I get that screen, watchlist loads, movies list loads but TV shows just goes busy and stops without showing the list.

Have tried this multiple times on fresh installs, clearing all cache too on a Mac, an Android phone and an Android Minix u9-h, same result on all.

Error section:

**Comment by fungusfeet** [comment]
Created a new TV list with one show and that works fine.  Maybe my old one was too big (134 shows!).  I'll either move all to a new one and see if it works or split/prune.  Guess that's resolved.

**Comment by 123Venom** [comment]
Lists loads fine.  My wife's list has 39 entries in it and is rather old, not as big as yours though.  Still should not be an issue.  Might be a threads issue looking at that log.  If I have some time later on I'll monkey with that test4 list I created to see if I can trigger it.  I'd be careful trading off tvshows.py with redux.  My version is quite different with new sort functions and counters that redux does not do so some functionality will be lost using it.  

I know where to start looking with your issue and I'll see if I can duplicate it.

![Watch_list](https://user-images.githubusercontent.com/46383815/57416087-aced2300-71cc-11e9-8ca3-28399830bb0a.JPG)

**Comment by 123Venom** [comment]
I added 140 items to my test4 list and was able to finally duplicate your issue.  Found the problem and it is a threads issue I fixed.  I'll try to push an update tonight or tomorrow for it.  The problem is also these exo forks were never equipped to handle that many list items and do not create a "Next" page to shorten the list and quicken the load time.  I added additional caching ability to Trakt lists which should help but a list that size gets tough for threads.  I may add to my to-do list to make those massive lists into "Next" page break items.

**Comment by 123Venom** [comment]
If you want to test the solution open "MY" tvshows.py. Fine the "worker" function, should be line 1009.  5th line down says "maximum = 50" so replace that with "maximum = total + 10".  This will pad the number of list items and cover cases of huge lists and not get carried away on small lists either.
![max](https://user-images.githubusercontent.com/46383815/57423050-57227600-71e0-11e9-8453-4d1e26566cc1.JPG)

**Comment by fungusfeet** [comment]
Working perfectly, thanks for looking into it.
