### ISSUE TITLE
Request api languages 

### ISSUE THREAD

**Issue by Tinuz97** [123Venom/zips#4]
Could you add Dutch to the api languages.

Like this :+1:

<setting id="api.language" type="select" label="32316" values="Dutch|English|German" default="English" />

Thx

**Comment by Tinuz97** [comment]
<setting id="api.language" type="select" label="32316" values="Dutch|English|German" default="English" />

**Comment by Tinuz97** [comment]
Weird, I am not allowed to post a piece of code 😕

**Comment by 123Venom** [comment]
I'll work on it.  Not as simple as adding it as an option.  Requires a complete strings.po translation file but I'll develop one.

**Comment by Tinuz97** [comment]
Strings.po is only needed of you also want the addon itself in Dutch. 

I added just simple added the word Dutch (for the api language, not for the complete addon) 

To the api in resources/settings.xml in venom, and works great. 

So like this :

<setting id="api.language" type="select" label="32316" values="Dutch|English|German" default="English" />


In that way the movie or show info is in Dutch (not the addon, for that you also need strings indeed) 

⁣BlueMail voor Android downloaden ​

Op 9 mei 2019 00:48, om 00:48, 123Venom <notifications@github.com> schreef:

**Comment by 123Venom** [comment]
I assumed if you wanted dutch api you'd only want interface also but pretty sure I know how to dial that in..lol

**Comment by Tinuz97** [comment]
Just trying to help lol 😅
Already converted the complete addon to Dutch for myself, a Dutch Reddit user wanted the api in Dutch, and did not know how to reach you 😉

Already fixed the complete addon in Dutch, also the api. 
⁣BlueMail voor Android downloaden ​

Op 9 mei 2019 02:01, om 02:01, 123Venom <notifications@github.com> schreef:
