### ISSUE TITLE
TMDB In theaters broken

### ISSUE THREAD

**Issue by Tinuz97** [123Venom/zips#5]
self.theaters_link is broken, just fyi (wrong link)

**Comment by 123Venom** [comment]
The TMDb link is called "Now Playing" in the interface with TMDb icon/logo and it does not use self.theaters_link as an action...that's IMDb's link.  Look again.  TMDb's "Now Playing"  uses self.tmdb_nowplaying_link per movies.py init string.  Works fine here.  I will say I've done extensive code changes the last month and even openmeta/openinfo moved so even my repo was updated to 1.6
![tmdb_movies2](https://user-images.githubusercontent.com/46383815/57408927-f6317880-71b4-11e9-9012-532e7fd2303c.JPG)
![tmdb_movies](https://user-images.githubusercontent.com/46383815/57408936-fdf11d00-71b4-11e9-9ba6-86cfee759050.JPG)
![tmdb_now_playing](https://user-images.githubusercontent.com/46383815/57408953-09444880-71b5-11e9-9868-0751a6f39a7c.JPG)
![Now_playing](https://user-images.githubusercontent.com/46383815/57408991-25e08080-71b5-11e9-9275-99310b21d399.JPG)



.  At this point it may be wise to do a fresh install.
