### ISSUE TITLE
Saved View Types

### ISSUE THREAD

**Issue by warmach1ne23** [123Venom/zips#6]
View Types would not save for shows and movies but it's fine for season and episodes.

**Comment by 123Venom** [comment]
I'll have a look at it and get back to you.

**Comment by warmach1ne23** [comment]
TY

**Comment by 123Venom** [comment]
what skin?  I just tested in Aeon Nox: Silvo that I use and it saves fine.  To be sure I did both movies and tv shows in a different setting to verify they were changed and different, which they were.  I have Aura skin and gave that a test.  It did not save any setting I tried, however...the work around here is the use the "lock" feature at top of screen to lock the view setting you chose and that retains the view setting.  this is highly skin dependent so I'll dig into it further but the two skins I have I got to work, Silvo with ease but Aura needed some guidance.  Let me know what skin.

**Comment by 123Venom** [comment]
ok I got Aura to work within my view settings but that skin you MUST still use the lock feature after setting the view type you want.  Aura will not save it as is and must be locked.  Just something in the skin I can't over-ride.  Is that the skin you use?

**Comment by warmach1ne23** [comment]
I'm using aeon nox silvo 7.0.1. What I just notice is I'll save it as icon view and it's fine on page 1 but now when I skip to the next pages it'll be in the list view then when I go back a page it'll show the icon view I've set. IDK seems like a weird bug of some sort. Doesn't occur in any other exodus forks I use.

**Comment by 123Venom** [comment]
That's really odd asa I use that exact skin as my primary and this issue does not happen to me.  I looked at this once again for you further but first I'm going to say the typical person is going to tell you the "views" function that controls this is not something we modders touch.  So I took 3 addons, mine as one....I then placed them side by side and compared the "views" function line by line.  It's identical and it's not a function I've ever touched nor prob ever will.  I wish I could replicate it but I can not.  My only advise is try Aftermatch to not just clear out addon cache but system cache as well as there is a views.db file you normally can't access but Aftermath can...clear it!  That has to be the issue
![Capture](https://user-images.githubusercontent.com/46383815/57990195-41c80a00-7a72-11e9-8e39-973baa43736b.JPG)

**Comment by 123Venom** [comment]
After allot of time messing around trying to replicate your issue I was successful.  If you go into my tools setting under "view types" and set a view for movies...then while in movies attempt to change the view type...go to next page and it will resort to the view type you set in my settings.  That's how that option is suppose to work and over-ride the skin.  I suggest you go there and set your desired view type and try again.  Someone set it there so it's locked to that view type and subsequent pages keep resorting to it but I got out of it.

**Comment by 123Venom** [comment]
I'm going to add an option to "clear view types"...this will force a reset and if I had that now that would fix your issue.  No fork cache clears views.db.  you could either do as I outlined above to set it as you want or delete the views.db from your userdata/plugin.video.venom folder.  That will manually reset it and toss out any views someone may have toyed with and set as a default for tv shows....I'm sure that's your issue because it's the only way i got it to keep resorting to another view setting on next page.  And if someone did do that then ya...this issue would only happen in Venom because they forced it to use another view type.

**Comment by warmach1ne23** [comment]
OK I see, thank ya. Love all the work you've put in so far. I also have a small suggestion in the movie and tv shows list there's multiple popular or airing today sections for trakt, tmdb, imdb so I'm suggesting for better clarity to add the respective tags to them eg. popular (trakt), airing today (tmdb) or something of the sorts.

**Comment by 123Venom** [comment]
add tags?  You didn't notice the icon change to IMDb, TMDb, Trakt logos?  I might have missed one here or there but that's clear as day where it's coming from.  I do however have in the works to add settings page option to turn off ones that are a multiple from difference index sources so you can choose which you prefer of the 3 I have now.

**Comment by 123Venom** [comment]
![logos](https://user-images.githubusercontent.com/46383815/58033751-0de0f900-7af3-11e9-912a-82ee2b6527e7.JPG)

**Comment by 123Venom** [comment]
Just finishing up on adding discart from fanart.tv.  A nice touch to the player.  Nobody is using this piece of artwork

![discart2](https://user-images.githubusercontent.com/46383815/58133764-b6c24d80-7bf2-11e9-8657-638fdd8726a5.JPG)
