### ISSUE TITLE
Request (not a issue) 

### ISSUE THREAD

**Issue by Tinuz97** [123Venom/zips#7]
Sort by size (high to low filesize) would be awesome :100:

**Comment by 123Venom** [comment]
I'll look into adding that sort method but sadly won't be any time soon.  Right now I'm back to working on UpNext integration and have a ways to go on that alone.  After that my plan was to modify the source select from a dir list to also include an settings option for a window style list.  A window list has far more control over labels (size and color) and it's a bit off work, might include this sort request into that work.

**Comment by Tinuz97** [comment]
Window style, with sort by size (like Seren) is even more awesome 👌

**Comment by 123Venom** [comment]
I honestly have a preference for Auto-play w/premptive termination.  With both a PM & RD account the scrape to play is way faster and rarely do I get a play failure, plus much more wife friendly.  When a play failure does occur I just use the cm option "Source Select" to bypass Auto-play for that instance.  But that source dir list in exo forks does suck...always thought it was ugly as shit.  My recent mod to multiline was a temp means to cure the ugliness.
